server.port: 8083
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/smart-home
    username: smart-home-admin
    password: smart-home-admin
